"""The single classification boundary — TECH_STACK v2 §Classification.

    classify(report_text) -> Outcome

Everything above this line (routes, aggregation, the frontend) is unaware of which classifier
answered. Everything below it is swappable. That separation is the reason the backend could be
finished before the models existed, and the reason swapping them in costs one function call.

The pipeline, in order:

    cache hit? ──yes──> return it (only real answers are ever stored)
        │no
        ├─ primary classifier, with a hard timeout
        │     ├─ returns valid ClassificationResult ─> cache + return
        │     ├─ returns something Pydantic rejects  ─> retry ONCE
        │     │        └─ rejected again ────────────> baseline, is_fallback=True
        │     └─ raises / times out ─────────────────> baseline, is_fallback=True
        └─ baseline answers are NOT cached: a degraded answer must never become
           permanent, and the cache has no expiry

Two things this buys us for free, both of which are answers to hostile questions:

* **Schema-failure rate is measured, not hoped for.** `metrics()` counts how often the model
  returned something the schema rejected. Hallucination becomes a logged number rather than an
  unbounded risk.
* **Degraded mode is honest.** `is_fallback` rides all the way to the UI, which says
  "degraded mode — keyword baseline" in plain words rather than quietly serving worse answers.

MEMBER 2: you do not edit this file. You write two functions and register them — see
`register_primary` / `register_baseline` below, and docs/handoff/member-2.md.
"""

from __future__ import annotations

import logging
import time
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeout
from dataclasses import dataclass
from typing import Any, Callable, Protocol

from pydantic import ValidationError

from . import cache
from .config import get_settings
from .schemas import ClassificationResult
from .stub import MODEL_VERSION as STUB_VERSION, classify_stub

log = logging.getLogger(__name__)


class Classifier(Protocol):
    """What Member 2 registers.

    Return either a `ClassificationResult` or a plain dict/JSON object. A dict is validated
    here, so an LLM returning a malformed field triggers the retry-then-fallback path rather
    than propagating a half-built object into the database.
    """

    version: str

    def __call__(self, report_text: str) -> ClassificationResult | dict[str, Any]: ...


@dataclass(frozen=True)
class Outcome:
    result: ClassificationResult
    model_version: str
    is_fallback: bool
    from_cache: bool
    latency_ms: int


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------
# Both slots default to the keyword stub so the API is fully functional today. Member 2
# replaces them one at a time; nothing else in the codebase changes.


def _stub(report_text: str) -> ClassificationResult:
    return classify_stub(report_text)


_stub.version = STUB_VERSION  # type: ignore[attr-defined]

_primary: Classifier = _stub  # type: ignore[assignment]
_baseline: Classifier = _stub  # type: ignore[assignment]

_counters = {"calls": 0, "cache_hits": 0, "schema_failures": 0, "retries": 0, "fallbacks": 0}


def register_primary(classifier: Classifier) -> None:
    """Register the real classifier — the structured Claude call. Needs a `.version`."""
    global _primary
    _primary = classifier
    log.info("primary classifier registered: %s", getattr(classifier, "version", "?"))


def register_baseline(classifier: Classifier) -> None:
    """Register the TF-IDF baseline. This is what answers when the primary cannot."""
    global _baseline
    _baseline = classifier
    log.info("baseline classifier registered: %s", getattr(classifier, "version", "?"))


def active_versions() -> dict[str, str]:
    return {
        "primary": getattr(_primary, "version", "unknown"),
        "baseline": getattr(_baseline, "version", "unknown"),
    }


def metrics() -> dict[str, Any]:
    """Schema-failure rate as a measured number. Surfaced on /meta."""
    calls = _counters["calls"]
    return {
        **_counters,
        "schema_failure_rate": round(_counters["schema_failures"] / calls, 4) if calls else 0.0,
        "fallback_rate": round(_counters["fallbacks"] / calls, 4) if calls else 0.0,
        "cache_size": cache.size(),
        **active_versions(),
    }


def reset_metrics() -> None:
    for key in _counters:
        _counters[key] = 0


# ---------------------------------------------------------------------------
# The pipeline
# ---------------------------------------------------------------------------


def _coerce(raw: ClassificationResult | dict[str, Any]) -> ClassificationResult:
    """Validate whatever the classifier returned. Raises ValidationError on malformed output."""
    if isinstance(raw, ClassificationResult):
        return raw
    return ClassificationResult.model_validate(raw)


# Long-lived pool. Deliberately NOT a `with` block: the context manager shuts down waiting for
# running threads, so a timed-out call would still block until the slow request finished — a
# timeout that does not actually return control is worse than no timeout, because you believe
# you are protected. On timeout we abandon the worker and answer from the baseline.
_pool = ThreadPoolExecutor(max_workers=4, thread_name_prefix="classify")


def _call_with_timeout(classifier: Classifier, report_text: str, seconds: float):
    """Hard wall-clock limit.

    The API call itself may honour a timeout, but a wedged connection or a slow retry inside a
    client library will not — and on stage the difference between 10 seconds and 40 is the
    difference between a working demo and a dead one.
    """
    future = _pool.submit(classifier, report_text)
    try:
        return future.result(timeout=seconds)
    except FutureTimeout:
        future.cancel()  # abandoned if already running; we do not wait for it
        raise


def classify(report_text: str, *, use_cache: bool = True) -> Outcome:
    started = time.perf_counter()
    _counters["calls"] += 1
    settings = get_settings()

    if use_cache:
        hit = cache.get(report_text)
        if hit is not None:
            result, model_version = hit
            _counters["cache_hits"] += 1
            return Outcome(
                result=result,
                model_version=model_version,
                is_fallback=model_version == getattr(_baseline, "version", None) and _primary is not _baseline,
                from_cache=True,
                latency_ms=max(1, int((time.perf_counter() - started) * 1000)),
            )

    result: ClassificationResult | None = None
    is_fallback = False
    model_version = getattr(_primary, "version", "unknown")

    for attempt in (1, 2):
        try:
            result = _coerce(_call_with_timeout(_primary, report_text, settings.llm_timeout_seconds))
            break
        except ValidationError as exc:
            # The model answered, but not in the shape the schema demands.
            _counters["schema_failures"] += 1
            log.warning("schema validation failed (attempt %s): %s", attempt, exc.error_count())
            if attempt == 1:
                _counters["retries"] += 1
                continue
        except FutureTimeout:
            log.warning("primary classifier timed out after %ss", settings.llm_timeout_seconds)
            break
        except Exception as exc:  # noqa: BLE001 - any failure means degrade, never 500
            log.warning("primary classifier failed: %s: %s", type(exc).__name__, exc)
            break

    if result is None:
        # Degraded mode. The baseline is local, so this path has no network dependency at all.
        _counters["fallbacks"] += 1
        is_fallback = True
        model_version = getattr(_baseline, "version", "unknown")
        try:
            result = _coerce(_baseline(report_text))
        except Exception as exc:  # noqa: BLE001
            # If even the local baseline fails, the honest answer is "we could not assess this",
            # never a fabricated classification.
            log.error("baseline classifier failed: %s: %s", type(exc).__name__, exc)
            raise ClassificationUnavailable(str(exc)) from exc

    if use_cache and not is_fallback:
        # Never cache a degraded answer.
        #
        # This used to cache the baseline result too, so that "a demo that fell back stays
        # consistent". The cost of that consistency is that it is permanent: the cache has
        # no TTL, so one bad minute from the model pins the stub answer to that report
        # forever, on every future call, including from the deployed API. There is no path
        # back except deleting the row by hand.
        #
        # It is not theoretical. A run against a groq client that could not call the model
        # at all wrote 56 stub answers into the cache under the current prompt version.
        # Every one of those reports then returned the stub instantly, with no error, no
        # log line and no network call - which is also why the failure was so hard to see:
        # calling the classifier directly worked, and calling it through the cache did not.
        #
        # A fallback that is recomputed next time and succeeds is not an inconsistency. It
        # is the system recovering, which is what degraded mode is supposed to allow.
        cache.put(report_text, result, model_version)

    return Outcome(
        result=result,
        model_version=model_version,
        is_fallback=is_fallback,
        from_cache=False,
        latency_ms=max(1, int((time.perf_counter() - started) * 1000)),
    )


class ClassificationUnavailable(RuntimeError):
    """Both classifiers failed. Surfaced as 503 — never as a guessed label."""
